# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4137d17dadae5e0eb3420ea588e7de681df492155a036f77e0cde8e8ebc87f21df928b3b30bb7e0e8a4cfec7bf04611e3abe4107b307f8a43636da9621fc98a

test:
  secret_key_base: aff93db7d63603cc2ea2bee6fbf94c5a3e1197252c9cda0f062821a0a13a745240f896e6c41a2f9fbb4c6e0479a74b0710e7765239ace2e26b2bae825548abbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
